<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_ArrayDint" Id="{1b6e5608-6533-03be-0953-370b0ccf8f1c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ArrayDint VAR_GENERIC CONSTANT nLength: DINT:= 1; END_VAR
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	nValues:			ARRAY [0..nLength - 1] OF DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>