<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Cylinder" Id="{0e789de7-7fe2-0204-3f8e-57ce5ee55d5b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cylinder EXTENDS FB_Component
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bInHome					AT%I*:		BOOL;
	bInWork					AT%I*:		BOOL;
	bToHome					AT%Q*:		BOOL;
	bToWork					AT%Q*:		BOOL;
	fbTimeout:				TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Disable" Id="{084d4cc3-90c8-03fb-3f3b-46af82c7c547}">
      <Declaration><![CDATA[METHOD PUBLIC M_Disable : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Execute" Id="{3442fc22-050d-094c-015a-424104d580c9}">
      <Declaration><![CDATA[METHOD PROTECTED M_Execute : BOOL // Return state complete
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_ToHome" Id="{e25a0059-ac3f-0fc7-183d-9c8c2fedf38c}">
      <Declaration><![CDATA[METHOD PUBLIC M_ToHome : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_ToWork" Id="{f6a4519f-a033-0321-07a0-e77d6b54d36a}">
      <Declaration><![CDATA[METHOD PUBLIC M_ToWork : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Cylinder">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder.M_Disable">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder.M_Execute">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder.M_ToHome">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cylinder.M_ToWork">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>