<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_DXDT" Id="{552cd1c3-fed9-0678-0801-e00b65d10145}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DXDT
VAR_INPUT
	nX:			INT;
	nT:			INT;
	nLimit:		INT;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>