<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ModuleLogger" Id="{a6fc589b-3f77-0dc8-1c02-65bea2758222}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ModuleLogger IMPLEMENTS I_Logger
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Log" Id="{ff8b0304-c1ca-062b-059f-da74ab423126}">
      <Declaration><![CDATA[METHOD M_Log
VAR_INPUT
	stEvent	: 		ST_Event;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_ModuleLogger">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_ModuleLogger.M_Log">
      <LineId Id="58" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>