<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_MessageBox" Id="{d7235460-dafe-0f48-1a0c-f9a6c027f422}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_MessageBox
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	ID:				ID;
	Message:		STRING(255);
	Arguments:		STRING(255);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_MessageBox">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>