<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ProgressBar" Id="{b42bd780-f298-0c3f-1cc9-ca2665c7b984}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ProgressBar
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ProgressBar">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>