<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Module02" Id="{7130c2ee-1b68-031f-0cb9-d3880326d9d5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Module02 EXTENDS FB_ModuleBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	bTest:		Bool;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// https://github.com/PeterZerlauth/Tc3_Component]]></ST>
    </Implementation>
    <Method Name="M_Cycle" Id="{2f9a1a6b-1508-09a6-3fd9-70645b3639e3}">
      <Declaration><![CDATA[METHOD PUBLIC M_Cycle
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.M_Cycle();

//P_Event.M_AddSTRING('Test');
//P_Event.M_Warning('Some Warning %s', '');]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Initialise" Id="{f4a73143-e348-0683-2834-f813a57a2dab}">
      <Declaration><![CDATA[METHOD PROTECTED M_Initialise
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.M_Initialise();

P_Identifier:= 'M002';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Module02">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Module02.M_Cycle">
      <LineId Id="5" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="6" Count="0" />
    </LineIds>
    <LineIds Name="FB_Module02.M_Initialise">
      <LineId Id="24" Count="0" />
      <LineId Id="110" Count="0" />
      <LineId Id="105" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>