<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Cycle" Id="{e74cce6f-550c-444b-8cdf-19b824901777}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Cycle IMPLEMENTS I_Cycle
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Cycle" Id="{c23b40fd-4755-4d58-9e6c-63dc34a4b87e}">
      <Declaration><![CDATA[METHOD PUBLIC M_Cycle
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Cycle">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Cycle.M_Cycle">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>