<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{2d4d4998-19ee-0f89-2021-34d743efb262}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbModule1:	FB_Module01;
	fbModule2:	FB_Module02;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
fbModule1.M_Cycle();
fbModule2.M_Cycle();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>