<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="Component" Id="{fbc04b37-722b-0472-1a67-731cdd256460}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Component
VAR
	fbComponent1:			FB_Component;
	fbTestsuite1:			FB_Testsuite;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbTestsuite1();

fbComponent1.M_Cycle();

CASE fbTestsuite1.P_Testcase OF
	
	E_Testcase.Start:
		CASE fbComponent1.P_State OF
			E_State.Stopped:;
			
			E_State.Aborted, E_State.Holded:
				fbComponent1.M_RequestState(E_RequestState.Reset);
				
			ELSE
				fbComponent1.M_RequestState(E_RequestState.Stop);
				
		END_CASE
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Stopped, fbComponent1.P_State, 'E_State.Stopped');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Stopped)', '', 10);	
	
	10:	
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Start), 'Start');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Execute, fbComponent1.P_State, 'E_State.Execute');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Start)', '', 20);
		
	20:
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Stop), 'Stop');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Stopped, fbComponent1.P_State, 'E_State.Stop');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Stop)', '', 30);
		
	30:	
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Start), 'Start');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Execute, fbComponent1.P_State, 'E_State.Execute');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Start)', '', 50);
		
	50:	
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Abort), 'Abort');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Aborted, fbComponent1.P_State, 'E_State.Aborted');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Abort)', '', 60);
		
	60:
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Reset), 'Reset');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Stopped, fbComponent1.P_State, 'E_State.Stopped');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Reset)', '', 70);
		
	70:	
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Start), 'Start');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Execute, fbComponent1.P_State, 'E_State.Execute');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Start)', '', 80);	
	
	80:	
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Hold), 'Hold');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Holded, fbComponent1.P_State, 'E_State.Hold');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Hold)', '', 90);		

	90:
		fbTestsuite1.P_Assert.M_Equals_BOOL(TRUE, fbComponent1.M_RequestState(E_RequestState.Reset), 'Reset');
		fbTestsuite1.P_Assert.M_Equals_INT(E_State.Stopped, fbComponent1.P_State, 'E_State.Idle');
		fbTestsuite1.M_Testcase(fbComponent1.P_Info.P_Class, T#1S, 'fbComponent.M_RequestState(E_RequestState.Reset)', '', E_Testcase.Done);		
		
	E_Testcase.Done:;
	
END_CASE]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>